context:
  name: Salt
  version: "4.0.4"
  author: mhekkel

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ author }}/${{ name|lower }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8d67f4bb63eb7de937a9b8705f4442a2a5958b3baed2cb6c693df892c88836e8

build:
  number: 0
  skip: not linux
  script: |
    set -exo pipefail
    cmake -S . -B build -G Ninja \
      ${CMAKE_ARGS} \
      -DBUILD_DOCUMENTATION=ON
    cmake --build build --parallel ${CPU_COUNT}
    ./build/salt -i --prefix ${PREFIX}

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - myst-parser
    - pkg-config
    - sphinx
  host:
    - libgxrio
    - libmcfp
    - libmgui
    - libpinch
    - libzeep
    - maartens_resource_compiler
  run: []
  run_exports: []  # No shared libraries to worry about

tests:
  - script:
      - salt --version
      - salt --help

about:
  homepage: "https://github.com/mhekkel/salt"
  summary: "Terminal with built-in SSH"
  description: |
    Salt is a terminal emulator with built-in SSH.
    It is currently available as an executable that uses GTK4 on Linux,
    but it once was a Windows application.
    The library used for the GUI is still cross platform so it might one day return to Windows as well.
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://github.com/mhekkel/salt

extra:
  recipe-maintainers:
    - eunos-1128
